### ISSUE TITLE
Question: how much would it take to support Ruby 2.7?

### ISSUE THREAD

**Issue by prikha** [lib-ruby-parser/ruby-bindings#16]
Noticed a bit of an inconsistency:

Gem requires Ruby 2.6 by the spec:
https://github.com/lib-ruby-parser/ruby-bindings/blob/master/lib-ruby-parser.gemspec#L18

However once loaded it checks current version and raises an exception when RUBY_VERSION is not in the list(3.2, 3.1, 3.0). 

```rb
There was an error while trying to load the gem 'lib-ruby-parser'. (Bundler::GemRequireError)
Gem Load Error is: [lib-ruby-parser] Unsupported ruby-version 2.7
Backtrace for gem load error is:
```

https://github.com/lib-ruby-parser/ruby-bindings/blob/master/lib/lib-ruby-parser.rb#L298

It seems we can eliminate the inconsistency. 

And while on it seems that there is a fare share of projects using older Rubies and still be interested in performant Ruby parser. Is it something we could expect? It's known that 2.7 is nearing it's EOL, which is still a good case to automate a bit of code digging by using parser like this one.

**Comment by iliabylich** [comment]
> Gem requires Ruby 2.6 by the spec:

You are right, it should require `>= 3.0`. Would you like to send a PR?

> And while on it seems that there is a fare share of projects using older Rubies and still be interested in performant Ruby parser. Is it something we could expect?

Sorry, I'm not going to maintain multiple compilation scripts for deprecated versions of Ruby. Test/release process is insanely complex at the moment (you can see it for example from this CI run: https://github.com/lib-ruby-parser/ruby-bindings/actions/runs/4483051039) and I don't want to make it even more complex and fragile.

Ruby 2.7 is deprecated for almost a year now and it will stop receiving any (even security) updates in a week, so I think it's ok that it's not supported.
