### ISSUE TITLE
Add ways to efficiently traverse nodes

### ISSUE THREAD

**Issue by prikha** [lib-ruby-parser/ruby-bindings#20]
I'm looking for a way to efficiently work with AST produced by parser. With `parser` gem you could call `#children` on any node and use it to traverse the tree. 

In case of `lib-ruby-parser` I cant seem to find a good way to receive parser events or to traverse the tree. Should AST accept a visitor? Or maybe there is a mechanism already?

**Comment by iliabylich** [comment]
> With parser gem you could call #children on any node and use it to traverse the tree.

it's possible to do the same with code generation (`codegen` binary), there could be a `children` method, one for each node class.

> Or maybe there is a mechanism already?

no, there's nothing built-in
